name: weather_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1 ## ステート管理のためのフレームワーク
  dio: ^5.4.3+1 ## HTTPリクエストのための強力なDartのHTTPクライアント
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  envied: ^0.5.4+1
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.4
  riverpod_annotation: ^2.3.5
  retrofit: ^4.1.0
  flutter_keyboard_visibility: ^6.0.0
  go_router: ^14.2.1
  logger: ^2.5.0
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9 ## freezedやその他のソースコード生成パッケージ（freezedを含む）を使うために必要なパッケージ
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1
  riverpod_generator: ^2.4.0
  retrofit_generator: ^9.1.4

flutter:
  
  uses-material-design: true
  assets: 
    - assets/images/clouds-4215608_1280.jpg

