name: weather_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1 ## ステート管理のためのフレームワーク
  dio: ^5.4.3+1 ## HTTPリクエストのための強力なDartのHTTPクライアント
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  envied: ^0.5.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9 ## freezedやその他のソースコード生成パッケージ（freezedを含む）を使うために必要なパッケージ
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1

flutter:
  
  uses-material-design: true

