name: weather_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1 
  envied: ^0.5.4+1
  firebase_analytics: ^11.4.1
  firebase_core: ^3.10.1
  firebase_crashlytics: ^4.3.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_native_splash: ^2.4.3
  flutter_riverpod: ^2.5.1 
  gap: ^3.0.1
  go_router: ^14.2.1
  http_mock_adapter: ^0.6.1
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mockito: ^5.4.4
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  cloud_functions: ^5.3.4

dev_dependencies:
  build_runner: ^2.4.9 
  envied_generator: ^0.5.4+1
  freezed: ^2.5.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4
  riverpod_generator: ^2.4.0
  firebase_core_platform_interface: ^5.4.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/splash/
