name: Firebase Functions CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions 

    env:
      NODE_ENV: dev  # テスト環境を示す変数
      FIREBASE_PROJECT_ID: weatherapptest-f7454  # テスト用のFirebaseプロジェクト

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 

      - name: Install dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Firebase credentials
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_DEV" | base64 --decode > $HOME/service-account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json" >> $GITHUB_ENV
        env:
          FIREBASE_SERVICE_ACCOUNT_DEV: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}

      - name: Configure Test Environment
        run: |
          echo "OPENWEATHERMAP_API_KEY_DEV=${{ secrets.OPENWEATHERMAP_API_KEY_DEV }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT_ID=${{ env.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "NODE_ENV=${{ env.NODE_ENV }}" >> $GITHUB_ENV

      - name: Verify Firebase project access
        run: firebase projects:list --json | jq '.[].projectId' | grep "$FIREBASE_PROJECT_ID" || echo "Project not found!"

      - name: Run unit tests
        run: npm test
