name: Flutter CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set JAVA_HOME for Gradle
        run: echo "org.gradle.java.home=$JAVA_HOME" >> android/gradle.properties

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true

      - name: Create .env file
        run: |
          echo "OPENWEATHERMAP_API_KEY_DEV=${{ secrets.OPENWEATHERMAP_API_KEY_DEV }}" >> .env
          echo "OPENWEATHERMAP_API_KEY_STG=${{ secrets.OPENWEATHERMAP_API_KEY_STG }}" >> .env
          echo "OPENWEATHERMAP_API_KEY_PROD=${{ secrets.OPENWEATHERMAP_API_KEY_PROD }}" >> .env

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test

      - name: Build APK (Development)
        run: flutter build apk --dart-define=FLAVOR=dev

      - name: Build APK (Staging)
        if: github.event_name == 'push'
        run: flutter build apk --dart-define=FLAVOR=stg

      - name: Build APK (Production)
        if: github.event_name == 'push'
        run: flutter build apk --dart-define=FLAVOR=prod
